# Generated by Django 5.2.1 on 2025-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudCompleto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'ordering': ['id_producto'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
