# Generated by Django 5.2.1 on 2025-05-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudCompleto', '0002_productos_delete_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True, 'ordering': ['id_producto'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
